### ISSUE TITLE
bug in demo.py

### ISSUE THREAD

**Issue by yl-jiang** [jianzhnie/pyramidbox_pytorch#3]
the flowing code is in your 'models.pyramidbox.py':
    
```python
if not self.is_infer:
    output = (face_mbox_loc, face_mbox_conf,
                      head_mbox_loc, head_mbox_conf)
 else:
    output = self.detect(face_mbox_loc, self.softmax(face_mbox_conf))
```
but the function `self.detect()` needs three parameters in your script 'layers.functions.detection.py'

```python
class Detect(Function):
    def __init__(self, cfg):
          ...
    def forward(self, loc_data, conf_data, prior_data):
```

so, when i run 'demo.py', the flowing error reported:

```
TypeError: forward() missing 1 required positional argument: 'prior_data'
```

**Comment by yl-jiang** [comment]
i found that  use this [repository](https://github.com/yxlijun/Pyramidbox.pytorch) with Pytorch1.3 can running successful.

**Comment by sunzhe09** [comment]
@yl-jiang how did you solved it?
