### ISSUE TITLE
运行demo.py时出错

### ISSUE THREAD

**Issue by huyutao3550346** [jianzhnie/pyramidbox_pytorch#5]
你好，我成功的训练出了模型。但是在运行demo.py的时候出现了一个bug。

Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    detect(net, path, args.thresh)
  File "demo.py", line 73, in detect
    y = net(x)
  File "/home/huyutao/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huyutao/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/huyutao/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huyutao/face_mask_detect/pyramidbox_pytorch/models/pyramidbox.py", line 262, in forward
    self.softmax(face_mbox_conf))
TypeError: forward() missing 1 required positional argument: 'prior_data'

我查看了下源代码，是在pyramidbox.py中的261行。output = self.detect(face_mbox_loc, self.softmax(face_mbox_conf))少传了一个参数
Detect class貌似需要3个参数：loc_data, conf_data, prior_data；
请问下，prior_data这个参数如何传递？

如果我的理解有误，也请告知解决这个bug的方法。。。谢谢。

**Comment by chenwuxing** [comment]
碰到了一样的错误

**Comment by huyutao3550346** [comment]
@chenwuxing 我换了一个git项目 https://github.com/yxlijun/Pyramidbox.pytorch 就能跑通了，效果应该是一样的。

**Comment by chenwuxing** [comment]
三口油


| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月2日 19:04，huyutao3550346<notifications@github.com> 写道：

@chenwuxing 我换了一个git项目 https://github.com/yxlijun/Pyramidbox.pytorch 就能跑通了，效果应该是一样的。

**Comment by chenwuxing** [comment]
朋友你上次给的那个pyramidbox项目，我自己训练之后跑demo时会出现cuda out of memory的错误，但是我的电脑是2080ti，不应该不够啊，你有出现这种问题么
| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月2日 20:08，wuxing<chenwuxing87@163.com> 写道：
三口油


| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月2日 19:04，huyutao3550346<notifications@github.com> 写道：

@chenwuxing 我换了一个git项目 https://github.com/yxlijun/Pyramidbox.pytorch 就能跑通了，效果应该是一样的。

**Comment by huyutao3550346** [comment]
请确认两点:
1.如果你只有一个显卡的话，运行train.py的时候将—multigpu设为false
2.出现cuda out of memory的错误，是显存不够了，可以试试将train.py --batch_size参数设置的小一点，你用4试试，默认的是16。即train.py --batch_size 4。
我是有四个T100的显卡。所以开了多gpu和使用16的batch_size。

**Comment by huyutao3550346** [comment]
@chenwuxing
训练没问题？拿模型运行demo.py的时候显示cuda out of memory？

**Comment by chenwuxing** [comment]
非常感谢您的回复，我使用这个项目训练时没有问题，只有单卡2080ti，但是在跑demo.py时会报错，我找了半天错误也没法定位出来，不知道您跑demo时有出现这样的问题么


| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月6日 18:31，huyutao3550346<notifications@github.com> 写道：

请确认两点:
1.如果你只有一个显卡的话，运行train.py的时候将—multigpu设为false
2.出现cuda out of memory的错误，是显存不够了，可以试试将train.py --batch_size参数设置的小一点，你用4试试，默认的是16。即train.py --batch_size 4。
我是有四个T100的显卡。所以开了多gpu和使用16的batch_size。

**Comment by chenwuxing** [comment]
如果您没有出现这样的错误我再重新找下错误吧，我看项目底下也没有人和我一样的错误，很是奇怪
| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月6日 18:33，huyutao3550346<notifications@github.com> 写道：

训练没问题？拿模型运行demo.py的时候显示cuda out of memory？

**Comment by huyutao3550346** [comment]
你看看训练出来的weight有多大。然后用nvidia-smi看看显存是否被占用？

**Comment by chenwuxing** [comment]
模型文件218m，我跑demo时是关了其他训练程序的，没有占用GPU


| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月6日 18:37，huyutao3550346<notifications@github.com> 写道：

你看看训练出来的weight有多大。然后用nvidia-smi看看显存是否被占用？

**Comment by huyutao3550346** [comment]
这就很奇怪了。。模型大小也是正常的。没碰到过这样的问题。。

**Comment by chenwuxing** [comment]
确实奇怪，不过还是非常感谢您的回复，请问下可以留一下您的邮箱么，后面有问题可以向您发邮件请教么


| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月6日 18:45，huyutao3550346<notifications@github.com> 写道：

这就很奇怪了。。模型大小也是正常的。没碰到过这样的问题。。

**Comment by huyutao3550346** [comment]
请教谈不上，有问题大家可以交流交流。864346635@qq.com 这是我的邮箱，也可以直接git联系。

**Comment by chenwuxing** [comment]
收到，非常感谢！


| |
chenwuxing87
|
|
chenwuxing87@163.com
|
签名由网易邮箱大师定制
在2020年12月6日 18:55，huyutao3550346<notifications@github.com> 写道：

请教谈不上，有问题大家可以交流交流。864346635@qq.com 这是我的邮箱，也可以直接git联系。

**Comment by jianzhnie** [comment]
谢谢大家的指正，问题找到了，我已经修复了 demo 的 bug
